#include <unistd.h> 
#include <fcntl.h>  
#include <stdio.h>
#include <stdint.h> 
#define KYBERBYTES 32 //for KyberKEM
// Step 1 : generates a random seed of 32 bytes
int main(void)
{
    int fd;
    uint8_t seed[KYBERBYTES]; //the seed is 32 bytes long
    // dev/urandom are special files that provide random nums from PRNG
    fd = open("/dev/urandom", O_RDONLY); 
    if (fd < 0) 
    { 
        perror("error /dev/urandom"); 
        close(fd);
        return 1; 
    }
    ssize_t r = read(fd, seed, sizeof seed); //use that file to generate random numbers
    if (r < 0)
    {
        perror("error read");
        close(fd);
        return 1;
    }
    for (size_t i = 0; i < sizeof seed; i++) printf("%02x", seed[i]); //print the generated bytes in hexa (each byte)
    printf("\n");
    close(fd);

    return 0;
}